// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jLAmXkGdPPYDvKpL9j3cJd
// Component: APao_xwWny
import * as React from "react"
import { Link } from "gatsby"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Button from "../../Button" // plasmic-import: 16yj8MRmRBT/component
import { useScreenVariants as useScreenVariantskILw5UiAaS1UF } from "./PlasmicGlobalVariant__Screen" // plasmic-import: kILw5uiAaS1uF/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_hecto.module.css" // plasmic-import: jLAmXkGdPPYDvKpL9j3cJd/projectcss
import * as sty from "./PlasmicNewPage2.module.css" // plasmic-import: APao_xwWny/css
import Icon2Icon from "./icons/PlasmicIcon__Icon2" // plasmic-import: UAy27vUVGueJ/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3" // plasmic-import: TgLbINC6PndC/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg" // plasmic-import: aExR7mqu1-8/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg" // plasmic-import: g1j_XxrLjbNK/icon
import imageIAtipjAePwY from "./images/image.jpeg" // plasmic-import: IAtipjAEPwY/picture
import image2EP5I02UKSaT from "./images/image2.jpeg" // plasmic-import: eP5I02uKSaT/picture
import image3D2VOkmt4ZLp from "./images/image3.jpeg" // plasmic-import: d2vOKMT4zLP/picture
import image4DrbVbi4Ayyi from "./images/image4.jpeg" // plasmic-import: DRBVbi4AYYI/picture
import image5JaJ9QiPRkQa from "./images/image5.jpeg" // plasmic-import: JaJ9qiPRkQA/picture
import image61JWz4FzZitQ from "./images/image6.jpeg" // plasmic-import: 1jWz4FzZitQ/picture
import image7Tpyz12WfSwe from "./images/image7.jpeg" // plasmic-import: Tpyz12wfSWE/picture
import image8DfyHQyXnnXr from "./images/image8.jpeg" // plasmic-import: dfyHQyXnnXr/picture
import image9Mmx30Bhmnt7 from "./images/image9.jpeg" // plasmic-import: Mmx30Bhmnt7/picture
import image10CjCb683PoJq from "./images/image10.jpeg" // plasmic-import: CjCB683poJQ/picture

export const PlasmicNewPage2__VariantProps = new Array()

export const PlasmicNewPage2__ArgProps = new Array()

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn())

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise
  })

export function Head() {
  return <></>
}

function PlasmicNewPage2__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const $ctx = ph.useDataEnv?.() || {}
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args])
  const $props = {
    ...args,
    ...variants,
  }

  const currentUser = p.useCurrentUser?.() || {}
  const [$queries, setDollarQueries] = React.useState({})
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantskILw5UiAaS1UF(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__xm8I6)}>
            <div className={classNames(projectcss.all, sty.freeBox__hbpb8)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__nEqi)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__b8V48)}
                >
                  {true ? (
                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___8YeT1
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      <Icon2Icon
                        className={classNames(projectcss.all, sty.svg__eRkC6)}
                        role={"img"}
                      />
                    </p.PlasmicLink>
                  ) : null}

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__pFrzA)}
                  >
                    <p.Stack
                      as={p.PlasmicLink}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__nY8HF
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {false ? (
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__xcNr1)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__imxnl
                        )}
                      >
                        {"About Us"}
                      </div>

                      {false ? (
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__ycDjn)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={p.PlasmicLink}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__e9Mx
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {false ? (
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__pAru0)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ihPal
                        )}
                      >
                        {"Features"}
                      </div>

                      {false ? (
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__gL3Ja)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={p.PlasmicLink}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___4NzqZ
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {false ? (
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__xjVPx)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__frPj8
                        )}
                      >
                        {"Pricing "}
                      </div>

                      {false ? (
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__qwNPu)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={p.PlasmicLink}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__aXsre
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {false ? (
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__rhtVl)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__egb43
                        )}
                      >
                        {"Contact"}
                      </div>

                      {false ? (
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__wcjOs)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={p.PlasmicLink}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__w1YQ
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {false ? (
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg___6IcX)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__orTp5
                        )}
                      >
                        {"Blog"}
                      </div>

                      {false ? (
                        <Icon3Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___5NmH1
                          )}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__wo4O3
                      )}
                      endIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__ajRk0)}
                          role={"img"}
                        />
                      }
                      shape={"rounded"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__dLQp)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__crR
                        )}
                      >
                        {"Get started"}
                      </div>
                    </Button>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox___0FpUo)}>
            <div
              data-plasmic-name={"pageBanner"}
              data-plasmic-override={overrides.pageBanner}
              className={classNames(projectcss.all, sty.pageBanner)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__j9WNy)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__rpSx)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__oJjJ0)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__zwqnp)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"Blog"}
                      </h1>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xD9G
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,"
                        }
                      </div>
                    </p.Stack>
                  </div>

                  <div className={classNames(projectcss.all, sty.column__uiMb)}>
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__r3Cxa)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "100%"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "lazy"
                          : "lazy"
                      }
                      src={
                        hasVariant(globalVariants, "screen", "mobileOnly")
                          ? {
                              src: imageIAtipjAePwY,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined,
                            }
                          : {
                              src: imageIAtipjAePwY,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined,
                            }
                      }
                    />
                  </div>
                </p.Stack>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__p231Q)}>
              <div className={classNames(projectcss.all, sty.freeBox___7VMov)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__kiiw2)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column___9Xuev)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__lxqUq)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__sfyH)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___7Fupn)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image2EP5I02UKSaT,
                            fullWidth: 509,
                            fullHeight: 340,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__hqrnI
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__wa1Ox
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__s1KIz
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dZHa2
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__s9QRp
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__g4Qm9
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__rrwxM
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__spZhM
                              )}
                            >
                              {"Read post"}
                            </div>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__vm1Jp)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__hZle8)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___4CdJh
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ryq9F)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image3D2VOkmt4ZLp,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__ltfC)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__nm3Cb
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__bJor4
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__vsEK
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button___1Oka
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__btu8E
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__yEkrs
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ouQfK
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__yC8Uc)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___0B7Fw
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__k92Z8
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__lJ1EN)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image4DrbVbi4Ayyi,
                            fullWidth: 1920,
                            fullHeight: 1080,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__g1D7P
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fzp3T
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__wgbEp
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oI67H
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__jUnz
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__qjrG
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__jiWDu
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__g4PUl
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___7Jj3V)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__yrMip)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__uaEwI
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__q9C5V)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image5JaJ9QiPRkQa,
                            fullWidth: 640,
                            fullHeight: 360,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__lRvX)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___7Im
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__hoxDy
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rVXvd
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__gfvI
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__eHnDp
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__xtQg9
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__kSy1P
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column___7E37H)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__sqzRb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__umish
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__tltPc)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image61JWz4FzZitQ,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___9W7W5
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ddKF
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__kD6FA
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ofjPe
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__k0Ed9
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__b8RHr
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__f41QS
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xZ4W3
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__hs4HW)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___77Xc3
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__aiAcx
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__p1Pyt)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: image7Tpyz12WfSwe,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ekwKi
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ilWh8
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__aqKlN
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xc6Qu
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__htd80
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__mrxgv
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ptXXa
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__r4U3G
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__mceWn)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__nSuV)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__gQmyW
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__hLHdO)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: imageIAtipjAePwY,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__avgsh
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__igziA
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__dpdKv
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tpJcd
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__xUPmB
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___2F8EL
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__bKGx2
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hoTfc
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__ufnMo)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__b2WyW)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__qPcNc
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ge9H0)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: imageIAtipjAePwY,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__pzGv)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jtOy
                          )}
                        >
                          <h4
                            className={classNames(
                              projectcss.all,
                              projectcss.h4,
                              projectcss.__wab_text,
                              sty.h4__hLxmu
                            )}
                          >
                            {hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "Customer Loyalty Programs That Stick"
                              : "Blog heading dummy"}
                          </h4>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__p9UfK
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                            }
                          </div>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button___3T0Uu
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___5T4Q
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__sgys
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___3E2Ie
                              )}
                            >
                              {"Learn more"}
                            </div>
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__j1JRa)}>
            <div
              data-plasmic-name={"footerTop"}
              data-plasmic-override={overrides.footerTop}
              className={classNames(projectcss.all, sty.footerTop)}
            >
              <div
                data-plasmic-name={"container"}
                data-plasmic-override={overrides.container}
                className={classNames(projectcss.all, sty.container)}
              >
                <div className={classNames(projectcss.all, sty.columns__bey5K)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__aIbXq)}
                  >
                    <Icon2Icon
                      className={classNames(projectcss.all, sty.svg__xrFjQ)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qyj6Z
                      )}
                    >
                      {
                        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                      }
                    </div>
                  </p.Stack>

                  <div
                    className={classNames(projectcss.all, sty.column___2NoU0)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___8IMhG
                      )}
                    >
                      {"Menu"}
                    </h5>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__a4Llz
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {"Privacy Policy"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__qCx5B
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {"Terms of Service"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__rhga3
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {"Pricing "}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__ojeVe
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {"Contact"}
                    </p.PlasmicLink>

                    <p.PlasmicLink
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__dBmf9
                      )}
                      component={Link}
                      platform={"gatsby"}
                    >
                      {"Blog"}
                    </p.PlasmicLink>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__w1S2R)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__p2BFj
                      )}
                    >
                      {"Gallery"}
                    </h5>

                    <div
                      className={classNames(projectcss.all, sty.columns__vThbW)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__vWOo)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__byha1)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image8DfyHQyXnnXr,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__xGzCd
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ytiba)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image9Mmx30Bhmnt7,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___9St79
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__guStJ)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image10CjCb683PoJq,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.columns__l74Y)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__w0LvK
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__pN54C)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image8DfyHQyXnnXr,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__m6Hn0
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__d9Al1)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image9Mmx30Bhmnt7,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__hOz00
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__snIhN)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image10CjCb683PoJq,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"footerBottom"}
              data-plasmic-override={overrides.footerBottom}
              className={classNames(projectcss.all, sty.footerBottom)}
            >
              <div
                data-plasmic-name={"container2"}
                data-plasmic-override={overrides.container2}
                className={classNames(projectcss.all, sty.container2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zafBv
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "© Company Name. All rights reserved. This site proudly built with "
                      }
                    </React.Fragment>
                    {
                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__kfHo6
                        )}
                        component={Link}
                        href={"https://www.plasmic.app/"}
                        platform={"gatsby"}
                      >
                        {"Plasmic"}
                      </p.PlasmicLink>
                    }

                    <React.Fragment>{"."}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageBanner",
    "h1",
    "footerTop",
    "container",
    "footerBottom",
    "container2",
  ],

  pageBanner: ["pageBanner", "h1"],
  h1: ["h1"],
  footerTop: ["footerTop", "container"],
  container: ["container"],
  footerBottom: ["footerBottom", "container2"],
  container2: ["container2"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNewPage2__ArgProps,
          internalVariantPropNames: PlasmicNewPage2__VariantProps,
        }),

      [props, nodeName]
    )

    return PlasmicNewPage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicNewPage2"
  } else {
    func.displayName = `PlasmicNewPage2.${nodeName}`
  }
  return func
}

export const PlasmicNewPage2 = Object.assign(
  // Top-level PlasmicNewPage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageBanner: makeNodeComponent("pageBanner"),
    h1: makeNodeComponent("h1"),
    footerTop: makeNodeComponent("footerTop"),
    container: makeNodeComponent("container"),
    footerBottom: makeNodeComponent("footerBottom"),
    container2: makeNodeComponent("container2"),
    // Metadata about props expected for PlasmicNewPage2
    internalVariantProps: PlasmicNewPage2__VariantProps,
    internalArgProps: PlasmicNewPage2__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: "",
    },
  }
)

export default PlasmicNewPage2
/* prettier-ignore-end */
