// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jLAmXkGdPPYDvKpL9j3cJd
import * as React from "react"
import { CmsCredentialsProvider } from "@plasmicpkgs/plasmic-cms" // plasmic-import: OREVbGCcgN/codeComponent

export default function GlobalContextsProvider(props) {
  const { children, cmsCredentialsProviderProps } = props
  return (
    <CmsCredentialsProvider
      {...cmsCredentialsProviderProps}
      databaseId={
        cmsCredentialsProviderProps &&
        "databaseId" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseId
          : "qu2Atc6RwmZBHivoW3xVKa"
      }
      databaseToken={
        cmsCredentialsProviderProps &&
        "databaseToken" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseToken
          : "0a4SdiiXYzcmjjWWk6egX1Mevbg1Yp0rIb1m9FM91Ga5rvbMWQRKYeATJmQGOxCr9x6VPJOVdcwV33hBTheA"
      }
      host={
        cmsCredentialsProviderProps && "host" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.host
          : "https://studio.plasmic.app"
      }
      locale={
        cmsCredentialsProviderProps && "locale" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.locale
          : undefined
      }
    >
      {children}
    </CmsCredentialsProvider>
  )
}
