// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jLAmXkGdPPYDvKpL9j3cJd
// Component: HLCMdt64_9V
import * as React from "react"
import { Link } from "gatsby"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import HectoNav from "../../HectoNav" // plasmic-import: 1Xqtr1aGys/component
import Button from "../../Button" // plasmic-import: 16yj8MRmRBT/component
import { useScreenVariants as useScreenVariantskILw5UiAaS1UF } from "./PlasmicGlobalVariant__Screen" // plasmic-import: kILw5uiAaS1uF/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_hecto.module.css" // plasmic-import: jLAmXkGdPPYDvKpL9j3cJd/projectcss
import * as sty from "./PlasmicNewsletter3.module.css" // plasmic-import: HLCMdt64_9V/css
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg" // plasmic-import: g1j_XxrLjbNK/icon
import image14YhFYwAwD from "./images/image14.png" // plasmic-import: YhFYw-awD/picture
import airTravelerClubIconpngOXhQeqkJr from "./images/airTravelerClubIconpng.png" // plasmic-import: oXHQeqkJR/picture
import voltFmpng65KNczT0E from "./images/voltFmpng.png" // plasmic-import: 65kNczT0e/picture
import growthmentor2PngDbFq2ZnDc from "./images/growthmentor2Png.png" // plasmic-import: DBFq2ZNDc/picture
import image13Oy5YWPkj7 from "./images/image13.png" // plasmic-import: Oy5yWPkj7/picture
import logoUsdsvgOdeblsO1Yj from "./images/logoUsdsvg.svg" // plasmic-import: odeblsO1Yj/picture
import clipboardOutlinesvg5UIvmRlOr from "./images/clipboardOutlinesvg.svg" // plasmic-import: 5UIvmRLOr/picture
import searchsvgIWxwm9VuZ from "./images/searchsvg.svg" // plasmic-import: IWxwm9VuZ/picture
import peopleOutlinesvgHyxjcYqpG7 from "./images/peopleOutlinesvg.svg" // plasmic-import: hyxjcYqpG7/picture

export const PlasmicNewsletter3__VariantProps = new Array()

export const PlasmicNewsletter3__ArgProps = new Array()

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn())

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    await promise
  })

export function Head() {
  return (
    <>
      <meta name="twitter:card" content="summary" />
      <title key="title">{PlasmicNewsletter3.pageMetadata.title}</title>
      <meta
        key="og:title"
        property="og:title"
        content={PlasmicNewsletter3.pageMetadata.title}
      />

      <meta
        key="twitter:title"
        name="twitter:title"
        content={PlasmicNewsletter3.pageMetadata.title}
      />
    </>
  )
}

function PlasmicNewsletter3__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const $ctx = ph.useDataEnv?.() || {}
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args])
  const $props = {
    ...args,
    ...variants,
  }

  const currentUser = p.useCurrentUser?.() || {}
  const [$queries, setDollarQueries] = React.useState({})
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantskILw5UiAaS1UF(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              sty.root
            )}
          >
            <div className={classNames(projectcss.all, sty.freeBox__hiXbx)}>
              <div className={classNames(projectcss.all, sty.freeBox__vw0Zr)}>
                <HectoNav
                  data-plasmic-name={"hectoNav"}
                  data-plasmic-override={overrides.hectoNav}
                  className={classNames("__wab_instance", sty.hectoNav)}
                />

                <div className={classNames(projectcss.all, sty.freeBox__s2Jm)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__hIdx)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__haiVl)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__uzRmg
                        )}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__pdcQr
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#0506CF" }}
                            >
                              {"Reach your target market,"}
                            </span>
                            <React.Fragment>{"\n"}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FF4A03" }}
                            >
                              {"through trusted"}
                            </span>
                            <React.Fragment>{"\n"}</React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FF4A03" }}
                            >
                              {"newsletters."}
                            </span>
                          </React.Fragment>
                        </h1>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eYig
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#AFAFB8" }}
                            >
                              {
                                "Hecto is a platform to buy, sell and manage newsletter ads and sponsorships."
                              }
                            </span>
                          </React.Fragment>
                        </div>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rcQfR
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__mjTqb
                          )}
                          color={"secondary"}
                          endIcon={
                            <ArrowRightsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__pScZz
                              )}
                              role={"img"}
                            />
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sLkb
                            )}
                          >
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "#FF0000" }}
                              >
                                {"Buy Ads"}
                              </span>
                            </React.Fragment>
                          </div>
                        </Button>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__c3TC7
                          )}
                          endIcon={
                            <ArrowRightsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vT2Gj
                              )}
                              role={"img"}
                            />
                          }
                          link={
                            hasVariant(globalVariants, "screen", "mobileOnly")
                              ? "https://app.hecto.io/search"
                              : "https://hecto.io/creators"
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ojciv
                            )}
                          >
                            {"Sell Ads"}
                          </div>
                        </Button>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </div>
              </div>
            </div>

            {true ? (
              <section
                data-plasmic-name={"features"}
                data-plasmic-override={overrides.features}
                className={classNames(projectcss.all, sty.features)}
              >
                <div className={classNames(projectcss.all, sty.column___7Yu9J)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__r5Ndu)}
                  >
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__aiflW
                      )}
                    >
                      {"Newsletters \ntrusted by"}
                    </h2>

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__g3Nhc)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"200px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "http://s3.amazonaws.com/appforest_uf/f1612212968629x588639892014067800/hootsuite.png"
                      }
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__xzWoa)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"200px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://s3.amazonaws.com/appforest_uf/f1599861530959x149048109187747800/Logo-with-clearspace.png"
                      }
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__a4A8Z)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"200px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://s3.amazonaws.com/appforest_uf/f1612213380220x409371329433475100/email-octopus-logo.png"
                      }
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__oVubS)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"200px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://s3.amazonaws.com/appforest_uf/f1599862025614x593508823287736800/Monday.com-Logo.wine.png"
                      }
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__bmtl0)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"200px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={
                        "https://s3.amazonaws.com/appforest_uf/f1647471882824x158210612790481900/user_logo.svg"
                      }
                    />
                  </p.Stack>

                  <div
                    data-plasmic-name={"container4"}
                    data-plasmic-override={overrides.container4}
                    className={classNames(projectcss.all, sty.container4)}
                  >
                    <div
                      data-plasmic-name={"outerRow2"}
                      data-plasmic-override={overrides.outerRow2}
                      className={classNames(projectcss.all, sty.outerRow2)}
                    >
                      <div
                        data-plasmic-name={"row2"}
                        data-plasmic-override={overrides.row2}
                        className={classNames(projectcss.all, sty.row2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__lacmO
                          )}
                        >
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__prEmq
                              )}
                            >
                              <h1
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h1,
                                  projectcss.__wab_text,
                                  sty.h1__ela3D
                                )}
                              >
                                <React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#0506CF" }}
                                  >
                                    {"Generate leads"}
                                  </span>
                                  <React.Fragment>{"\n"}</React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#0506CF" }}
                                  >
                                    {"from "}
                                  </span>
                                  <React.Fragment>{""}</React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#FF4A03" }}
                                  >
                                    {"engaged "}
                                  </span>
                                  <React.Fragment>{"\n"}</React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#FF4A03" }}
                                  >
                                    {"email audiences"}
                                  </span>
                                  <React.Fragment>{""}</React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#0506CF" }}
                                  >
                                    {" "}
                                  </span>
                                </React.Fragment>
                              </h1>
                            </p.Stack>
                          ) : null}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__l7EwL
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__t6Fqd)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: image14YhFYwAwD,
                              fullWidth: 844,
                              fullHeight: 521,
                              aspectRatio: undefined,
                            }}
                          />
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"container5"}
                    data-plasmic-override={overrides.container5}
                    className={classNames(projectcss.all, sty.container5)}
                  >
                    <div
                      data-plasmic-name={"outerRow3"}
                      data-plasmic-override={overrides.outerRow3}
                      className={classNames(projectcss.all, sty.outerRow3)}
                    >
                      <div
                        data-plasmic-name={"row4"}
                        data-plasmic-override={overrides.row4}
                        className={classNames(projectcss.all, sty.row4)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__mkSdY
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___4EptU
                            )}
                          >
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__vhHgv)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: airTravelerClubIconpngOXhQeqkJr,
                                fullWidth: 201,
                                fullHeight: 202,
                                aspectRatio: undefined,
                              }}
                            />

                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__qHcOu)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: voltFmpng65KNczT0E,
                                fullWidth: 199,
                                fullHeight: 205,
                                aspectRatio: undefined,
                              }}
                            />

                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__rka6S)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: growthmentor2PngDbFq2ZnDc,
                                fullWidth: 192,
                                fullHeight: 195,
                                aspectRatio: undefined,
                              }}
                            />
                          </div>
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.column__wqEz2
                          )}
                        >
                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___5GTg
                              )}
                            >
                              <h1
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h1,
                                  projectcss.__wab_text,
                                  sty.h1___5Gv2V
                                )}
                              >
                                <React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#0506CF" }}
                                  >
                                    {"Build your campaign "}
                                  </span>
                                  <React.Fragment>{"\n"}</React.Fragment>
                                  <span
                                    className={
                                      "plasmic_default__all plasmic_default__span"
                                    }
                                    style={{ color: "#FF4A03" }}
                                  >
                                    {"across multiple newsletters"}
                                  </span>
                                </React.Fragment>
                              </h1>
                            </p.Stack>
                          ) : null}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            ) : null}

            <section className={classNames(projectcss.all, sty.columns__iju6R)}>
              <div className={classNames(projectcss.all, sty.column__etYgV)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__gtRdi)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__axzOg
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#0506CF" }}
                        >
                          {"Why use Hecto"}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#FF4A03" }}
                        >
                          {"?"}
                        </span>
                      </React.Fragment>
                    </h1>
                  </p.Stack>
                ) : null}

                <div className={classNames(projectcss.all, sty.columns__pAsib)}>
                  <div
                    data-plasmic-name={"reasonBox"}
                    data-plasmic-override={overrides.reasonBox}
                    className={classNames(projectcss.all, sty.reasonBox)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__wfIz6)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={"https://www.svgrepo.com/show/15349/chat.svg"}
                    />

                    <div
                      className={classNames(projectcss.all, sty.columns__h98Wi)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__llqYy
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__dbF09
                          )}
                        >
                          {"Protected privacy"}
                        </h4>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vhIBg
                          )}
                        >
                          {
                            "Don't give you contact details to make an enquiry. Message creators directly, right here on the platform"
                          }
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"reasonBox2"}
                    data-plasmic-override={overrides.reasonBox2}
                    className={classNames(projectcss.all, sty.reasonBox2)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__e0NnG)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: image13Oy5YWPkj7,
                        fullWidth: 452,
                        fullHeight: 452,
                        aspectRatio: undefined,
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.columns__c7KkO)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__kGEx8
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__xFqK
                          )}
                        >
                          {"Upfront Prices"}
                        </h4>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yt6J0
                          )}
                        >
                          {
                            "No need to request pricing information. See prices of ad packages [i]before [/i] you contact a newsletter. "
                          }
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"reasonBox3"}
                    data-plasmic-override={overrides.reasonBox3}
                    className={classNames(projectcss.all, sty.reasonBox3)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__v9Ka)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: logoUsdsvgOdeblsO1Yj,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1000000,
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.columns__tLMw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__utovB
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__p5Uu
                          )}
                        >
                          {"Pay Directly"}
                        </h4>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__i8WqJ
                          )}
                        >
                          {
                            "Don't give you contact details to make an enquiry. Message creators directly, right here on the platform"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className={classNames(projectcss.all, sty.columns__waU6V)}>
                  <div
                    data-plasmic-name={"reasonBox4"}
                    data-plasmic-override={overrides.reasonBox4}
                    className={classNames(projectcss.all, sty.reasonBox4)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ymEd2)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: clipboardOutlinesvg5UIvmRlOr,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1000000,
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.columns__xF28)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__nwZ8)}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__eUrwh
                          )}
                        >
                          {"Fast Submission"}
                        </h4>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cg2Kb
                          )}
                        >
                          {
                            "Don't give you contact details to make an enquiry. Message creators directly, right here on the platform"
                          }
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"reasonBox5"}
                    data-plasmic-override={overrides.reasonBox5}
                    className={classNames(projectcss.all, sty.reasonBox5)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__nqHsj)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: searchsvgIWxwm9VuZ,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1000000,
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.columns__wYg50)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__rEzl)}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4___0BILd
                          )}
                        >
                          {"Quality Control"}
                        </h4>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9FHpV
                          )}
                        >
                          {
                            "Don't give you contact details to make an enquiry. Message creators directly, right here on the platform"
                          }
                        </div>
                      </div>
                    </div>
                  </div>

                  <div
                    data-plasmic-name={"reasonBox6"}
                    data-plasmic-override={overrides.reasonBox6}
                    className={classNames(projectcss.all, sty.reasonBox6)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___8TKw5)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: peopleOutlinesvgHyxjcYqpG7,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1000000,
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.columns__liCpH)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__rDuW2
                        )}
                      >
                        <h4
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4__j7WlE
                          )}
                        >
                          {"Super Engagement"}
                        </h4>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uuik8
                          )}
                        >
                          {
                            "Don't give you contact details to make an enquiry. Message creators directly, right here on the platform"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {true ? (
              <section
                className={classNames(projectcss.all, sty.columns__ygArp)}
              >
                <div
                  data-plasmic-name={"outer"}
                  data-plasmic-override={overrides.outer}
                  className={classNames(projectcss.all, sty.outer)}
                >
                  <div
                    data-plasmic-name={"container"}
                    data-plasmic-override={overrides.container}
                    className={classNames(projectcss.all, sty.container)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__kFHrQ)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__fd2AQ
                        )}
                      >
                        {"To Make Requests For The\nFurther Information"}
                      </h2>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sRtFe
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                        }
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__hIxAk)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__koP3U
                        )}
                        color={"blue"}
                        link={"#"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tOpG
                          )}
                        >
                          {"Join With Now"}
                        </div>
                      </Button>
                    </div>
                  </div>
                </div>
              </section>
            ) : null}

            <div className={classNames(projectcss.all, sty.freeBox__upMkq)}>
              <div className={classNames(projectcss.all, sty.columns__v4YGy)}>
                <div className={classNames(projectcss.all, sty.column___9IfIe)}>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ahBlr
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000" }}
                      >
                        {"Ready to start your campaign?"}
                      </span>
                    </React.Fragment>
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c2Egn
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000" }}
                      >
                        {"Find the perfect newsletter for your brand"}
                      </span>
                    </React.Fragment>
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button___4Tlwp)}
                    color={"blue"}
                    endIcon={
                      <ArrowRightsvgIcon
                        className={classNames(projectcss.all, sty.svg__cabQl)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pz6F
                      )}
                    >
                      {"Search Newsletters"}
                    </div>
                  </Button>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.freeBox___1QhWx)}>
              <div
                data-plasmic-name={"footerBottom"}
                data-plasmic-override={overrides.footerBottom}
                className={classNames(projectcss.all, sty.footerBottom)}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox___4Qypc)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aGbxC
                    )}
                  >
                    {"© Hecto. All rights reserved"}
                  </div>

                  <p.PlasmicLink
                    data-plasmic-name={"link"}
                    data-plasmic-override={overrides.link}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link
                    )}
                    component={Link}
                    platform={"gatsby"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3Km9W
                      )}
                    >
                      {"Privacy"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pZ8Jk
                      )}
                    >
                      {"Terms and Conditions"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mgTyW
                      )}
                    >
                      {"Contact Us"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eTrBf
                      )}
                    >
                      {"Blog"}
                    </div>
                  </p.PlasmicLink>
                </div>
              </div>
            </div>
          </p.Stack>
        ) : null}
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "hectoNav",
    "features",
    "container4",
    "outerRow2",
    "row2",
    "container5",
    "outerRow3",
    "row4",
    "reasonBox",
    "reasonBox2",
    "reasonBox3",
    "reasonBox4",
    "reasonBox5",
    "reasonBox6",
    "outer",
    "container",
    "footerBottom",
    "link",
  ],

  hectoNav: ["hectoNav"],
  features: [
    "features",
    "container4",
    "outerRow2",
    "row2",
    "container5",
    "outerRow3",
    "row4",
  ],

  container4: ["container4", "outerRow2", "row2"],
  outerRow2: ["outerRow2", "row2"],
  row2: ["row2"],
  container5: ["container5", "outerRow3", "row4"],
  outerRow3: ["outerRow3", "row4"],
  row4: ["row4"],
  reasonBox: ["reasonBox"],
  reasonBox2: ["reasonBox2"],
  reasonBox3: ["reasonBox3"],
  reasonBox4: ["reasonBox4"],
  reasonBox5: ["reasonBox5"],
  reasonBox6: ["reasonBox6"],
  outer: ["outer", "container"],
  container: ["container"],
  footerBottom: ["footerBottom", "link"],
  link: ["link"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNewsletter3__ArgProps,
          internalVariantPropNames: PlasmicNewsletter3__VariantProps,
        }),

      [props, nodeName]
    )

    return PlasmicNewsletter3__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicNewsletter3"
  } else {
    func.displayName = `PlasmicNewsletter3.${nodeName}`
  }
  return func
}

export const PlasmicNewsletter3 = Object.assign(
  // Top-level PlasmicNewsletter3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    hectoNav: makeNodeComponent("hectoNav"),
    features: makeNodeComponent("features"),
    container4: makeNodeComponent("container4"),
    outerRow2: makeNodeComponent("outerRow2"),
    row2: makeNodeComponent("row2"),
    container5: makeNodeComponent("container5"),
    outerRow3: makeNodeComponent("outerRow3"),
    row4: makeNodeComponent("row4"),
    reasonBox: makeNodeComponent("reasonBox"),
    reasonBox2: makeNodeComponent("reasonBox2"),
    reasonBox3: makeNodeComponent("reasonBox3"),
    reasonBox4: makeNodeComponent("reasonBox4"),
    reasonBox5: makeNodeComponent("reasonBox5"),
    reasonBox6: makeNodeComponent("reasonBox6"),
    outer: makeNodeComponent("outer"),
    container: makeNodeComponent("container"),
    footerBottom: makeNodeComponent("footerBottom"),
    link: makeNodeComponent("link"),
    // Metadata about props expected for PlasmicNewsletter3
    internalVariantProps: PlasmicNewsletter3__VariantProps,
    internalArgProps: PlasmicNewsletter3__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Hecto | Newsletter advertising, simplified",
      description: "",
      ogImageSrc: "",
      canonical: "",
    },
  }
)

export default PlasmicNewsletter3
/* prettier-ignore-end */
